# Serving Deep Neural Network through Django

This notebook is the simple neural network we build for this workshop. It comprises of using specified parameters to classify mobile phones in price range.

The dataset for this work is gotten from https://www.kaggle.com/iabhishekofficial/mobile-price-classification



In [1]:
#import dependencies

import numpy as np
import pandas as pd


data = pd.read_csv("dataset/train.csv")
data.head(5)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [2]:
data.describe

<bound method NDFrame.describe of       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
5              1859     0          0.5         1   3       0          22   
6              1821     0          1.7         0   4       1          10   
7              1954     0          0.5         1   0       0          24   
8              1445     1          0.5         0   0       0          53   
9               509     1          0.6         1   2       1           9   
10              769     1          2.9         1   0       0           9   
11             1520     1          2.2         0   5  

In [3]:
#convert pandas Dataframe to numpy array

X = data.iloc[:,:20].values
y = data.iloc[:,20:21].values



print(X)
print()
print(y)

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 1.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 1.000e+00]]

[[1]
 [2]
 [2]
 ...
 [3]
 [0]
 [3]]


In [4]:
#Normalizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = scaler.fit_transform(X)
print(X)
print()
print(y)

[[-0.90259726 -0.9900495   0.83077942 ... -1.78686097 -1.00601811
   0.98609664]
 [-0.49513857  1.0100505  -1.2530642  ...  0.55964063  0.99401789
  -1.01409939]
 [-1.5376865   1.0100505  -1.2530642  ...  0.55964063  0.99401789
  -1.01409939]
 ...
 [ 1.53077336 -0.9900495  -0.76274805 ...  0.55964063  0.99401789
  -1.01409939]
 [ 0.62252745 -0.9900495  -0.76274805 ...  0.55964063  0.99401789
   0.98609664]
 [-1.65833069  1.0100505   0.58562134 ...  0.55964063  0.99401789
   0.98609664]]

[[1]
 [2]
 [2]
 ...
 [3]
 [0]
 [3]]


In [5]:
#Perform one hot encoding of output class
from sklearn.preprocessing import OneHotEncoder

Y = data['price_range']
Y

0       1
1       2
2       2
3       2
4       1
5       1
6       3
7       0
8       0
9       0
10      3
11      3
12      1
13      2
14      0
15      0
16      3
17      3
18      1
19      1
20      3
21      3
22      1
23      0
24      1
25      2
26      3
27      3
28      2
29      0
       ..
1970    2
1971    1
1972    0
1973    3
1974    1
1975    3
1976    0
1977    2
1978    1
1979    1
1980    1
1981    1
1982    2
1983    2
1984    1
1985    3
1986    1
1987    0
1988    1
1989    1
1990    0
1991    3
1992    0
1993    3
1994    3
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [6]:
Y.unique()

array([1, 2, 3, 0], dtype=int64)

In [7]:

encoder = OneHotEncoder()
y = encoder.fit_transform(y).toarray()

print(y)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


C:\Users\Ashpot\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [8]:
#split test and train data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

### Now Build the Neural Network...

In [9]:
#import dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [10]:
model = Sequential()
model.add(Dense(16, input_dim=20, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(4, activation='softmax'))


model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

result = model.fit(X_train, y_train, epochs=100, batch_size=64)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
1800/1800 [==============================] - 0s 172us/step - loss: 1.4514 - accuracy: 0.2861
Epoch 2/100
1800/1800 [==============================] - 0s 23us/step - loss: 1.3677 - accuracy: 0.3156
Epoch 3/100
1800/1800 [==============================] - 0s 28us/step - loss: 1.3069 - accuracy: 0.3567
Epoch 4/100
1800/1800 [==============================] - 0s 23us/step - loss: 1.2480 - accuracy: 0.4194
Epoch 5/100
1800/1800 [==============================] - 0s 39us/step - loss: 1.1818 - accuracy: 0.4744
Epoch 6/100
1800/1800 [==============================] - 0s 33us/step - loss: 1.1065 - accuracy: 0.5372
Epoch 7/100
1800/1800 [==============================] - 0s 28us/step - loss: 1.0265 - accuracy: 0.5700
Epoch 8/100
1800/1800 [==============================] - 0s 26us/step - loss: 0.9462 - accuracy: 0.6178
Epoch 9/100
1800/1800 [========================

1800/1800 [==============================] - 0s 29us/step - loss: 0.0787 - accuracy: 0.9833
Epoch 74/100
1800/1800 [==============================] - 0s 29us/step - loss: 0.0773 - accuracy: 0.9844
Epoch 75/100
1800/1800 [==============================] - 0s 29us/step - loss: 0.0779 - accuracy: 0.9811
Epoch 76/100
1800/1800 [==============================] - 0s 41us/step - loss: 0.0750 - accuracy: 0.9861
Epoch 77/100
1800/1800 [==============================] - 0s 27us/step - loss: 0.0732 - accuracy: 0.9833
Epoch 78/100
1800/1800 [==============================] - 0s 23us/step - loss: 0.0724 - accuracy: 0.9850
Epoch 79/100
1800/1800 [==============================] - 0s 24us/step - loss: 0.0716 - accuracy: 0.9856
Epoch 80/100
1800/1800 [==============================] - 0s 24us/step - loss: 0.0693 - accuracy: 0.9872
Epoch 81/100
1800/1800 [==============================] - 0s 26us/step - loss: 0.0684 - accuracy: 0.9856
Epoch 82/100
1800/1800 [==============================] - 0s 26us/st

In [11]:
y_pred = model.predict(X_test)

#Convert predictions back to labels

pred = list()
for i in range(len(y_pred)):
    pred.append(np.argmax(y_pred[i]))
    

    
#Converting one hot encoded test label to label
test = list()
for i in range(len(y_test)):
    test.append(np.argmax(y_test[i]))
    
print(pred)
print()
print(test)

[0, 3, 3, 2, 3, 1, 0, 1, 1, 0, 3, 2, 3, 1, 2, 2, 3, 3, 2, 1, 2, 0, 3, 1, 2, 2, 3, 3, 3, 0, 1, 0, 2, 1, 1, 2, 2, 3, 2, 3, 2, 2, 2, 2, 3, 1, 0, 2, 3, 2, 2, 2, 0, 3, 0, 2, 2, 3, 2, 1, 2, 3, 0, 1, 0, 2, 1, 3, 1, 0, 2, 3, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0, 1, 3, 0, 2, 2, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, 3, 2, 2, 3, 0, 2, 3, 3, 0, 3, 3, 0, 1, 3, 3, 2, 0, 3, 3, 1, 0, 2, 3, 0, 1, 1, 2, 0, 2, 2, 2, 0, 0, 1, 0, 3, 1, 1, 3, 1, 2, 2, 3, 0, 0, 2, 0, 0, 3, 0, 2, 0, 0, 2, 2, 1, 0, 2, 2, 3, 3, 1, 2, 0, 0, 1, 0, 2, 2, 2, 0, 2, 3, 2, 1, 2, 1, 0, 2, 3, 2, 2, 3, 1, 3, 2, 1, 3, 3, 3, 3, 0, 0, 0, 3, 0, 0, 3, 1, 3, 3, 0, 1]

[0, 3, 3, 2, 3, 0, 0, 1, 1, 0, 3, 3, 3, 1, 2, 2, 3, 3, 2, 1, 2, 1, 3, 1, 2, 2, 3, 3, 3, 0, 1, 0, 2, 1, 1, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 1, 0, 2, 3, 2, 2, 2, 0, 3, 0, 2, 2, 3, 2, 1, 2, 3, 0, 1, 1, 2, 1, 3, 0, 0, 2, 3, 0, 0, 2, 1, 1, 1, 2, 3, 2, 0, 1, 3, 0, 2, 2, 2, 0, 1, 1, 0, 2, 0, 0, 0, 1, 3, 2, 3, 3, 0, 1, 3, 3, 0, 3, 3, 0, 1, 3, 3, 2, 1, 3, 3, 1, 0, 2, 3, 0, 1, 1, 2, 0, 2, 2, 2, 0, 0, 1, 0, 3

#### Comparing both result shows the accuracy of our neural network

Nevetheless, let's use accuracy score to test our model accuracy

In [12]:
from sklearn.metrics import accuracy_score

a = accuracy_score(pred, test)
print('Accuracy =', a*100)

Accuracy = 93.0


In [13]:
#save model
model.save("./saved_model/phone_price_classifier_model.h5")

#### What we could next

We could go ahead and plot a graph to show the training and validation accuracy, but for this we will need to redo our code and provide validation data for our neural network. But we will skip all that for this workshop as it doesn't necessarily impact on the performance of our model. 

So let's go ahead and deploy this model.